{% set name = "lmz" %}
{% set version = "0.1.12" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lmz-{{ version }}.tar.gz
  sha256: cf6b65efeaadec9d1c69d5286c7a0965eacab3b73eeaccec031b6537418a052c

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - lmz
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/smautner/listmapzip
  summary: return lists
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - smautner
